spring.application.name=statemachine
server.port=8081

# URL da API de mensagens
message.api.base-url=http://localhost:8080

spring.cache.type=caffeine
spring.cache.cache-names=mensagens
spring.cache.caffeine.spec=expireAfterWrite=5m